require('user.plugins')

require("user.alpha")
require('user.basic-plugins')
require('user.cmp')
require('user.colorscheme')
require('options')
require("lsp")
require('user.lualine')
require('user.nvim-tree')
require('user.nvim-treesitter')
require('user.vim-startify')
require('user.telescope-nvim')
