require 'plugin_configs.cmp'
require 'plugin_configs.initialize_basic_plugins'
require 'plugin_configs.telescope'
require 'plugin_configs.lualine'
require 'plugin_configs.trouble'
require 'plugin_configs.lightspeed'
require 'plugin_configs.harpoon'
